# Generated by Django 3.1.7 on 2021-05-22 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210521_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 1, 3, 8, 646386)),
        ),
    ]
