# Generated by Django 3.1.4 on 2021-05-11 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210511_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='code',
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='code',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 8, 26, 31, 663980)),
        ),
    ]
