# Generated by Django 3.1.4 on 2021-05-11 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210511_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_rate',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 9, 4, 59, 256969)),
        ),
    ]
