# Generated by Django 3.2.2 on 2021-05-13 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_coupon_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoupon',
            name='code',
        ),
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 11, 28, 30, 304312)),
        ),
    ]
