# Generated by Django 3.1.7 on 2021-05-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='product',
            new_name='room',
        ),
    ]
