# Generated by Django 3.2.2 on 2021-05-24 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productoption_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='room',
        ),
        migrations.AddField(
            model_name='product',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productoption'),
        ),
        migrations.AddField(
            model_name='room',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.service'),
        ),
    ]
