# Generated by Django 3.2.2 on 2021-05-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_roomtype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomservice',
            table='room_services',
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
