# Generated by Django 3.2.2 on 2021-05-13 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210513_0438'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicetype',
            table='service_types',
        ),
    ]
