# Generated by Django 3.2.2 on 2021-05-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_room_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitytype',
            table='activity_types',
        ),
    ]
