# Generated by Django 3.2.2 on 2021-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_activitytype_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_activity',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_dinning',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_room',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
